server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: false
  Debug: true
  ApiKey: sample-b4a2-4f1e-be66-5bdeb77e250a

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: user
  PostgresqlPassword: local
  PostgresqlDbname: local-test
  PostgresqlSslmode: true
  PgDriver: pgx

redis:
  RedisAddr: redis:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

s3:
  SpacesKey: sample
  SpacesSecret: secret
  SpacesEndpoint: https:localhost
  SpacesRegion: us
  SpacesBucket: /localbucket 

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

metrics:
  URL: localhost:7070
  ServiceName: api


mongodb:
  MongoURI: mongodb+srv://local

jaeger:
  Host: localhost:6831
  ServiceName: REST_API
  LogSpans: true