name: CICD
on:
  push:
    tags:
      - "v*.*.*-release"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev
        uses: actions/checkout@v3
        with:
          ref: docker

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV }}" > configs/local.yaml

      # Initiate your registry login here

      - name: Build Image
        run: docker build -f docker/Dockerfile -t ${{ secrets.REGISTRY_NAME }}/echo-api:latest .

      - name: Push Image
        run: docker push ${{ secrets.REGISTRY_NAME }}/echo-api:latest
